name: Build ROM
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build LineageOS for avicii
        uses: JeyKul/Build-Custom-ROM@main
        with:
          DEVICE_NAME: avicii
          ROM_NAME: lineage
          ROM_BRANCH: lineage-21.0
          BUILD_TYPE: userdebug
